#!/usr/bin/env node
// Integration tests — full data path: validate → export-md → check structure.
// These are the closest we get to E2E without a browser harness.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile, mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import Ajv2020 from 'ajv/dist/2020.js';
import { exportMarkdown } from '../scripts/export-md.lib.mjs';

const ROOT = new URL('..', import.meta.url).pathname;
const EXAMPLE_JSON = new URL('../examples/dashboard.ui.json', import.meta.url).pathname;
const SCHEMA_PATH = new URL('../schema/ui-blueprint.schema.json', import.meta.url).pathname;

async function makeValidator() {
  const schema = JSON.parse(await readFile(SCHEMA_PATH, 'utf8'));
  const ajv = new Ajv2020({ allErrors: true, strict: false });
  return ajv.compile(schema);
}

test('I1: full pipeline — validate dashboard, then export to markdown, then check sections', async () => {
  const validate = await makeValidator();
  const blueprint = JSON.parse(await readFile(EXAMPLE_JSON, 'utf8'));
  // 1. Validate
  assert.equal(validate(blueprint), true, 'dashboard must validate');
  // 2. Export to markdown
  const md = exportMarkdown(blueprint);
  // 3. Check that the output mentions every node id (proves no data loss in export)
  for (const node of blueprint.nodes) {
    assert.ok(md.includes(node.id), `markdown must reference node ${node.id}`);
  }
  // 4. Check that the output mentions every interaction
  for (const i of blueprint.interactions) {
    assert.ok(md.includes(i.action), `markdown must mention interaction action ${i.action}`);
  }
  // 5. Check that the output mentions every acceptance item
  for (const a of blueprint.acceptance) {
    assert.ok(md.includes(a.id), `markdown must mention acceptance ${a.id}`);
  }
});

test('I2: end-to-end CLI invocation produces a usable .ui.md file', async () => {
  // We invoke the same code path the CLI does: exportMarkdown() then write to disk.
  const blueprint = JSON.parse(await readFile(EXAMPLE_JSON, 'utf8'));
  const md = exportMarkdown(blueprint);
  const tmp = await mkdtemp(join(tmpdir(), 'aub-int-'));
  try {
    const out = join(tmp, 'out.md');
    await writeFile(out, md, 'utf8');
    const back = await readFile(out, 'utf8');
    assert.equal(back, md);
    assert.ok(back.length > 1000);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
});

test('I3: schema validation + exporter + lock generation all work on the same blueprint', async () => {
  const validate = await makeValidator();
  const blueprint = JSON.parse(await readFile(EXAMPLE_JSON, 'utf8'));
  assert.equal(validate(blueprint), true);

  const md = exportMarkdown(blueprint);
  assert.ok(md.length > 1000);

  // Simulate the lock generation (subset of what lock-blueprint.mjs does).
  const lockSubset = {
    node_ids: [...blueprint.nodes.map((n) => n.id)].sort(),
    counts: {
      nodes: blueprint.nodes.length,
      interactions: blueprint.interactions.length,
      acceptance: blueprint.acceptance.length,
    },
  };
  assert.equal(lockSubset.counts.nodes, 24);
  assert.equal(lockSubset.counts.interactions, 6);
  assert.equal(lockSubset.counts.acceptance, 11);
});

test('I4: pipeline catches a real error (missing required field fails validation AND breaks export)', async () => {
  const validate = await makeValidator();
  const blueprint = JSON.parse(await readFile(EXAMPLE_JSON, 'utf8'));
  delete blueprint.screen.platform;
  // 1. Validation must reject
  assert.equal(validate(blueprint), false, 'missing platform must fail validation');
  // 2. Exporter does NOT crash on the bad input (it just uses undefined → empty string)
  const md = exportMarkdown(blueprint);
  assert.ok(typeof md === 'string', 'exporter must not crash on partial input');
  assert.ok(md.includes('dashboard.overview'), 'screen.id is still present in bad input');
});

test('I5: full example suite (json + yaml) all validate and all export', async () => {
  const validate = await makeValidator();
  const EXAMPLE_YAML = new URL('../examples/dashboard.ui.yaml', import.meta.url).pathname;
  const yamlLib = await import('js-yaml');
  const json = JSON.parse(await readFile(EXAMPLE_JSON, 'utf8'));
  const yaml = yamlLib.load(await readFile(EXAMPLE_YAML, 'utf8'));
  assert.deepEqual(yaml, json, 'YAML and JSON examples must be equivalent');
  assert.equal(validate(json), true);
  assert.equal(validate(yaml), true);
  const mdFromJson = exportMarkdown(json);
  const mdFromYaml = exportMarkdown(yaml);
  assert.equal(mdFromJson, mdFromYaml, 'markdown export must be deterministic across input formats');
});

test('I6: lock file structure is correct (if present)', async () => {
  // The dashboard.ui.lock.json is generated by scripts/lock-blueprint.mjs.
  // If the file exists, verify its structure and that hashes are deterministic.
  const lockPath = new URL('../examples/dashboard.ui.lock.json', import.meta.url).pathname;
  let lock;
  try {
    lock = JSON.parse(await readFile(lockPath, 'utf8'));
  } catch {
    // Lock file not yet generated — skip (test is opt-in)
    return;
  }
  assert.ok(lock.version, 'lock must declare version');
  assert.ok(lock.source_file, 'lock must declare source_file');
  assert.ok(lock.exported_at, 'lock must declare exported_at');
  assert.ok(lock.hashes, 'lock must declare hashes');
  assert.equal(typeof lock.hashes.blueprint, 'string');
  assert.match(lock.hashes.blueprint, /^sha256:[a-f0-9]{64}$/);
  assert.equal(lock.counts.nodes, 24);
  assert.equal(lock.counts.interactions, 6);
  assert.equal(lock.counts.acceptance, 11);
});

test('I7: every node in the example is reachable from the root (no orphans)', async () => {
  const blueprint = JSON.parse(await readFile(EXAMPLE_JSON, 'utf8'));
  const root = blueprint.nodes.find((n) => n.parent_id === null);
  assert.ok(root, 'must have exactly one root node');
  // Count roots
  const roots = blueprint.nodes.filter((n) => n.parent_id === null);
  assert.equal(roots.length, 1, `must have exactly one root, found ${roots.length}`);
  // Walk the tree from root
  const visited = new Set();
  const walk = (id) => {
    if (visited.has(id)) return;
    visited.add(id);
    const n = blueprint.nodes.find((nn) => nn.id === id);
    if (n?.children) for (const c of n.children) walk(c);
  };
  walk(root.id);
  for (const n of blueprint.nodes) {
    assert.ok(visited.has(n.id), `node ${n.id} is not reachable from root — orphan`);
  }
});

test('I8: every node referenced by content.empty_state/loading_state/error_state exists', async () => {
  const blueprint = JSON.parse(await readFile(EXAMPLE_JSON, 'utf8'));
  const ids = new Set(blueprint.nodes.map((n) => n.id));
  for (const n of blueprint.nodes) {
    if (n.content?.empty_state) assert.ok(ids.has(n.content.empty_state), `${n.id} references missing empty_state`);
    if (n.content?.loading_state) assert.ok(ids.has(n.content.loading_state), `${n.id} references missing loading_state`);
    if (n.content?.error_state) assert.ok(ids.has(n.content.error_state), `${n.id} references missing error_state`);
  }
});
