// Re-exports from the root schema so the editor imports from one place.
export type {
  Blueprint,
  Screen,
  ScreenType,
  Platform,
  Viewport,
  UINode,
  Layout,
  Placement,
  ViewportId,
  DesignSystem,
  Size,
  Content,
  Interaction,
  InteractionTrigger,
  Responsive,
  ResponsiveViewport,
  ResponsiveRule,
  Acceptance,
  AcceptanceType,
  AcceptancePriority,
  VerificationMethod,
  ComponentType,
  ResolvedComponentType,
  ExtensionComponentType,
  NodeState,
  Provenance,
  SourceReference,
  Bindings,
  NodeValidation,
  InitialState,
} from '../../../schema/types';
